# Generated by Django 4.2 on 2025-09-11 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_app', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file', models.FileField(null=True, upload_to='submissions/')),
                ('status', models.CharField(choices=[('none', 'На проверке'), ('check_passed', 'Проверено'), ('check_failed', 'Отклонено'), ('done', 'Принято')], default='none', max_length=20)),
                ('status_text', models.TextField(null=True)),
                ('submission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_send_file.submissiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
