# Generated by Django 4.2 on 2024-02-22 15:35
from django.db import migrations

def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    # Use apps.get_model to avoid direct imports
    Group = apps.get_model("auth", "Group")
    BotCommand = apps.get_model("bot_app", "BotCommand")
    
    try:
        student_group = Group.objects.using(db_alias).get(name="Студент")
        
        if not BotCommand.objects.using(db_alias).filter(name='Отправить файл').exists():
            cmd = BotCommand.objects.using(db_alias).create(name='Отправить файл', description="Отправка файла отчета по дисциплине")
            cmd.applicable_groups.set([student_group])
    except Group.DoesNotExist:
        print("Warning: Group 'Студент' not found. Skipping creation of 'Отправить файл' command linkage.")

def reverse(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    BotCommand = apps.get_model("bot_app", "BotCommand")
    # Clean up command created in forward
    BotCommand.objects.using(db_alias).filter(name='Отправить файл').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("bot_send_file", "0001_initial"),
        ("bot_app", "0002_data"), # Dependency ensures groups exist
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
