# Generated by Django 4.2 on 2024-02-22 15:35
from datetime import datetime

from django.contrib.auth.models import Group, User
from django.db import migrations

from bot_app.models import BotCommand


def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    student_group = Group.objects.using(db_alias).get_or_create(name="Студент")

    cmd = BotCommand.objects.using(db_alias).create(name='Отправить файл', description="Отправка файла отчета по дисциплине")
    cmd.applicable_groups.set(student_group)

class Migration(migrations.Migration):

    dependencies = [
        ("bot_send_file", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
