# Generated by Django 4.2 on 2025-09-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_data'),
        ('bot_send_file', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='submissiontype',
            unique_together={('name', 'discipline')},
        ),
    ]
