# Generated by Django 4.2 on 2025-09-12 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_send_file', '0003_alter_submissiontype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
