# Generated by Django 6.0.1 on 2026-01-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_send_file', '0004_submission_created_at_submission_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
