# Generated by Django 6.0.4 on 2026-04-20 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_send_file', '0006_submissiontype_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
