# Generated by Django 6.0.4 on 2026-04-29 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_alter_authtoken_options_alter_botcommand_options_and_more'),
        ('bot_send_file', '0008_accept_late_and_is_late'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Сданная работа', 'verbose_name_plural': 'Сданные работы'},
        ),
        migrations.AlterModelOptions(
            name='submissiontype',
            options={'verbose_name': 'Тип задания', 'verbose_name_plural': 'Типы заданий'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(max_length=1000, null=True, upload_to='submissions/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='С опозданием'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('none', 'На проверке'), ('check_passed', 'Проверено'), ('check_failed', 'Отклонено'), ('done', 'Принято')], default='none', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status_text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_send_file.submissiontype', verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='accept_late',
            field=models.BooleanField(default=False, help_text='Если включено — поздние работы принимаются с пометкой «с опозданием».', verbose_name='Принимать после дедлайна'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='allowed_extensions',
            field=models.CharField(default='pdf,docx,doc,txt', help_text='Через запятую, например: pdf,docx,txt', max_length=255, verbose_name='Допустимые расширения'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=20, verbose_name='Макс. размер файла, МБ'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
