# Generated by Django 4.2.4 on 2025-03-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(related_name='events', through='bot_app.EventGroup', to='bot_app.group'),
        ),
    ]
