# Generated by Django 4.2 on 2024-02-22 15:35
from datetime import datetime

from django.contrib.auth.models import Group, User
from django.db import migrations

from bot_app.models import BotCommand


def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).get_or_create(name="Студент")
    Group.objects.using(db_alias).get_or_create(name="Сотрудник")
    Group.objects.using(db_alias).get_or_create(name="Сторонний")


class Migration(migrations.Migration):

    dependencies = [
        ("bot_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
