# Generated by Django 4.2.4 on 2025-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_event_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Без повторения'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='none', max_length=10),
        ),
    ]
