# Generated by Django 4.2.4 on 2025-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_event_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
