# Generated by Django 6.0.4 on 2026-04-29 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bot_app', '0005_authtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authtoken',
            options={'verbose_name': 'Токен авторизации бота', 'verbose_name_plural': 'Токены авторизации бота'},
        ),
        migrations.AlterModelOptions(
            name='botcommand',
            options={'verbose_name': 'Команда бота', 'verbose_name_plural': 'Команды бота'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Рассылка студентам', 'verbose_name_plural': 'Рассылки студентам'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь Telegram', 'verbose_name_plural': 'Пользователи Telegram'},
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='telegram_id',
            field=models.CharField(max_length=255, verbose_name='ID Telegram'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='botcommand',
            name='applicable_groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Кому показывать (роли)'),
        ),
        migrations.AlterField(
            model_name='botcommand',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='botcommand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название кнопки'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='groups',
            field=models.ManyToManyField(related_name='disciplines', to='auth.group', verbose_name='Учебные группы'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(related_name='disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Telegram'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
