# Generated by Django 4.2.4 on 2025-05-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_studentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Приду'), ('no', 'Не приду'), ('pending', 'Нет ответа')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.student')),
            ],
            options={
                'unique_together': {('event', 'student')},
            },
        ),
    ]
