# Generated by Django 6.0.4 on 2026-05-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_drop_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь мессенджера', 'verbose_name_plural': 'Пользователи мессенджера'},
        ),
    ]
