# Generated by Django 6.0.4 on 2026-04-29 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_send_file', '0009_alter_submission_options_and_more'),
        ('plagiarism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plagiarismreport',
            options={'verbose_name': 'Отчёт антиплагиата', 'verbose_name_plural': 'Отчёты антиплагиата'},
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='bert_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Совпадение по BERT, %'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='details',
            field=models.TextField(blank=True, default='', verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='matched_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarism_matches', to='bot_send_file.submission', verbose_name='Совпадение с работой'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='shingle_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Совпадение по шинглам, %'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='bot_send_file.submission', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='verdict',
            field=models.CharField(choices=[('pending', 'В очереди'), ('unsupported', 'Формат не поддерживается'), ('error', 'Ошибка проверки'), ('original', 'Оригинал'), ('suspicious', 'Подозрение на рерайт'), ('plagiarism', 'Плагиат')], default='pending', max_length=32, verbose_name='Вердикт'),
        ),
    ]
